# Generated by Django 5.0.6 on 2024-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dracula_home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsSee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(db_index=True, max_length=100, unique=True)),
                ('details', models.TextField()),
            ],
        ),
    ]
